// Canonical permission type identifiers (UPPERCASE plural) used across FE/BE
export const PERMISSION_TYPES = {
  WORKERS: 'WORKERS',
  CREATORS: 'CREATORS',
  STATUS_OWNERS: 'STATUS_OWNERS',
  EXECUTORS: 'EXECUTORS',
  FIELD_OWNERS: 'FIELD_OWNERS',
  FIELD_EDITORS: 'FIELD_EDITORS',
  FIELD_VIEWERS: 'FIELD_VIEWERS',
} as const;

export type PermissionTypeCanon = typeof PERMISSION_TYPES[keyof typeof PERMISSION_TYPES];

export const ALL_PERMISSION_TYPES: PermissionTypeCanon[] = [
  PERMISSION_TYPES.WORKERS,
  PERMISSION_TYPES.CREATORS,
  PERMISSION_TYPES.STATUS_OWNERS,
  PERMISSION_TYPES.EXECUTORS,
  PERMISSION_TYPES.FIELD_OWNERS,
  PERMISSION_TYPES.FIELD_EDITORS,
  PERMISSION_TYPES.FIELD_VIEWERS,
];



